name: Backend CI/CD

on: 
    push: 
        paths:
            - 'backend/**'
            - '.github/workflows/backend.yml'
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - run: |
                cd backend
                pip install flake8
                flake8 .
        
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - run: |
                cd backend
                pip install -r requirements.txt
                export PYTHONPATH=$(pwd)
                pytest

    deploy:
        runs-on: ubuntu-latest
        needs: test
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-2'
            APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
            ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
            S3_BUCKET: ${{ secrets.BACKEND_S3_BUCKET }}
        steps:
            - uses: actions/checkout@v3

            - name: Deploy to Elastic Beanstalk
              run: |
                cd backend
                zip -r app.zip .
                aws s3 cp app.zip s3://$S3_BUCKET/eb-builds/app-v${{ github.run_number }}.zip

                aws elasticbeanstalk create-application-version \
                    --application-name "$APPLICATION_NAME" \
                    --version-label "v-${{ github.run_number }}" \
                    --source-bundle S3Bucket="$S3_BUCKET",S3Key="eb-builds/app-v${{ github.run_number }}.zip"

                aws elasticbeanstalk update-environment \
                    --environment-name "$ENVIRONMENT_NAME" \
                    --version-label "v-${{ github.run_number }}"

