name: Frontend CI/CD

on:
    push:
        paths:
            - 'frontend/**'
            - '.github/workflows/frontend.yml'
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '18'
            - run: |
                cd frontend
                npm install
                npx eslint .

    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '18'
            - run: |
                cd frontend
                npm install
                npm test || echo "No tests found, skipping."
    
    deploy:
        runs-on: ubuntu-latest
        needs: test
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-2'
            S3_BUCKET: ${{ secrets.FRONTEND_S3_BUCKET }}
            CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: Build
              run: |
                cd frontend
                npm install
                npm run build

            - name: Upload to S3
              run: |
                aws s3 sync frontend/dist s3://$S3_BUCKET --delete

            - name: Invalidate CloudFront Cache
              run: |
                aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/*"

